export const EMPLOYEE_DETAILS_HEADER: any[] = [
    
    { field: 'id', header: 'ID' },
    { field: 'skill', header: 'Skill' },
    { field: 'resourceName', header: 'Resource Name' },
    { field: 'sowName', header: 'SOW Name' },
    { field: 'locationType', header: 'Location' },
    { field: 'clientManager', header: 'Client Manager' },
    { field: 'vendor', header: 'Vendor' },
    { field: 'project', header: 'Project' },
    { field: 'workLocation', header: 'Location' },
    { field: 'comments', header: 'Comments' },
    { field: 'msaRate', header: 'MSA Rate' },
    { field: 'rate', header: 'Rate ($)' },
    { field: 'year', header: 'Year' },
    { field: 'janHrs', header: 'Jan' },
    { field: 'febHrs', header: 'Feb' },
    { field: 'marHrs', header: 'Mar' },
    { field: 'aprHrs', header: 'Apr' },
    { field: 'mayHrs', header: 'May' },
    { field: 'junHrs', header: 'Jun' },
    { field: 'julHrs', header: 'Jul' },
    { field: 'augHrs', header: 'Aug' },
    { field: 'sepHrs', header: 'Sep' },
    { field: 'octHrs', header: 'Oct' },
    { field: 'novHrs', header: 'Nov' },
    { field: 'decHrs', header: 'Dec' },
    { field: 'totalHours', header: 'Total Hours' },
    { field: 'discountedFee', header: 'Fees ($) After Discount' }
]